server:
  port: 8090
spring:
  application:
    name: cart-service
  rabbitmq:
    virtual-host: leyou
    username: leyou
    password: 988513
    host: 139.9.195.148
  redis:
    host:  139.9.195.148
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: /Users/bystander/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称