server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: false
    register-with-eureka: false

#eureka-server集群的开发配置
#eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://127.0.0.1:10086/eureka
  #  server:
  #      enable-self-preservation: false     #关闭自我保护机制；
  #      eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）
  #  instance:
  #    lease-expiration-duration-in-seconds: 10  #失联时间
  #    lease-renewal-interval-in-seconds: 5      #间断联系时间

#eureka-client的相关配置
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  #    registry-fetch-interval-seconds: 5     代表每隔5秒fetch服务端维护的列表 缓存到本地