server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jackson
    username: root
    password: 988513
  application:
    name: user-service
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

    lease-renewal-interval-in-seconds: 30
