package com.koali.model;

import java.util.Date;

public class data {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.id
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.wendu
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer wendu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.shidu
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer shidu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.pm
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer pm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.so2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer so2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.no2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer no2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.co2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer co2;

    public Integer getFengsu() {
        return fengsu;
    }

    public void setFengsu(Integer fengsu) {
        this.fengsu = fengsu;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.o3
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private Integer o3;
    private Integer fengsu;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.time
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.type
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.id
     *
     * @return the value of data.id
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.id
     *
     * @param id the value for data.id
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.wendu
     *
     * @return the value of data.wendu
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getWendu() {
        return wendu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.wendu
     *
     * @param wendu the value for data.wendu
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setWendu(Integer wendu) {
        this.wendu = wendu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.shidu
     *
     * @return the value of data.shidu
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getShidu() {
        return shidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.shidu
     *
     * @param shidu the value for data.shidu
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setShidu(Integer shidu) {
        this.shidu = shidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.pm
     *
     * @return the value of data.pm
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getPm() {
        return pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.pm
     *
     * @param pm the value for data.pm
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setPm(Integer pm) {
        this.pm = pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.so2
     *
     * @return the value of data.so2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getSo2() {
        return so2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.so2
     *
     * @param so2 the value for data.so2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setSo2(Integer so2) {
        this.so2 = so2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.no2
     *
     * @return the value of data.no2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getNo2() {
        return no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.no2
     *
     * @param no2 the value for data.no2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setNo2(Integer no2) {
        this.no2 = no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.co2
     *
     * @return the value of data.co2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getCo2() {
        return co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.co2
     *
     * @param co2 the value for data.co2
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setCo2(Integer co2) {
        this.co2 = co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.o3
     *
     * @return the value of data.o3
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public Integer getO3() {
        return o3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.o3
     *
     * @param o3 the value for data.o3
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setO3(Integer o3) {
        this.o3 = o3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.time
     *
     * @return the value of data.time
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.time
     *
     * @param time the value for data.time
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.type
     *
     * @return the value of data.type
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public String getType() {
        return type;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @Override
    public String toString() {
        return "data{" +
                "id=" + id +
                ", wendu=" + wendu +
                ", shidu=" + shidu +
                ", pm=" + pm +
                ", so2=" + so2 +
                ", no2=" + no2 +
                ", co2=" + co2 +
                ", o3=" + o3 +
                ", time=" + time +
                ", type='" + type + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.type
     *
     * @param type the value for data.type
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}