package com.koali.model;

import java.util.Date;

public class user_sign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign.id
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign.name
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign.xuehao
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    private String xuehao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign.banji
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    private String banji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign.sign_time
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    private Date signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign.shiyanshi
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    private String shiyanshi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign.id
     *
     * @return the value of user_sign.id
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign.id
     *
     * @param id the value for user_sign.id
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign.name
     *
     * @return the value of user_sign.name
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign.name
     *
     * @param name the value for user_sign.name
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign.xuehao
     *
     * @return the value of user_sign.xuehao
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public String getXuehao() {
        return xuehao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign.xuehao
     *
     * @param xuehao the value for user_sign.xuehao
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public void setXuehao(String xuehao) {
        this.xuehao = xuehao == null ? null : xuehao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign.banji
     *
     * @return the value of user_sign.banji
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public String getBanji() {
        return banji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign.banji
     *
     * @param banji the value for user_sign.banji
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public void setBanji(String banji) {
        this.banji = banji == null ? null : banji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign.sign_time
     *
     * @return the value of user_sign.sign_time
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign.sign_time
     *
     * @param signTime the value for user_sign.sign_time
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign.shiyanshi
     *
     * @return the value of user_sign.shiyanshi
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public String getShiyanshi() {
        return shiyanshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign.shiyanshi
     *
     * @param shiyanshi the value for user_sign.shiyanshi
     *
     * @mbg.generated Mon Jun 03 19:44:31 CST 2019
     */
    public void setShiyanshi(String shiyanshi) {
        this.shiyanshi = shiyanshi == null ? null : shiyanshi.trim();
    }
}