server:
  port: 10087
spring:
  application:
    name: LeyouEurekaServer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  server:
    enable-self-preservation: false
