server:
  port: 5136
zuul:
  routes:
    user-service: /user-service/**
    random:
      path: /user/**
      serviceId: user-service
      strip-prefix: false  #进行路由转发的时候不会把user去掉，
    ignored-service:
      - consumer-service   #将这个服务的自动匹配转发的功能关掉
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka,http://127.0.0.1:10086/eureka
spring:
  application:
    name: zuul-gateway-service
ribbon: #控制下一级的链接和读取是否超时，去挑选比较轻松的服务
  ConnectionTimeout: 500
  ReadTimeout: 500

hystrix: #熔断超时机制超时设定
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1900
  circuitBreaker:
    sleepWindowInMilliseconds: 20
    requestVolumeThreshold: 5
    errorThresholdPercentage: 10