package com.koali.dao;



import com.koali.model.data;

import java.util.List;

public interface dataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    int insert(data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    data selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    List<data> selectAll( );
    List<data> selectbytime(String time);
    List<data> selectbytype(int type);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 21:58:05 CST 2019
     */
    int updateByPrimaryKey(data record);
}