package com.jason.generator.mappers;

import com.jason.generator.javaBean.data;
import java.util.List;

public interface dataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 22:54:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 22:54:05 CST 2019
     */
    int insert(data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 22:54:05 CST 2019
     */
    data selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 22:54:05 CST 2019
     */
    List<data> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Mon Jun 03 22:54:05 CST 2019
     */
    int updateByPrimaryKey(data record);
}