package com.jason.generator.mappers;

import com.jason.generator.javaBean.user_sign;
import com.jason.generator.javaBean.user_signExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface user_signMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    long countByExample(user_signExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int deleteByExample(user_signExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int insert(user_sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int insertSelective(user_sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    List<user_sign> selectByExample(user_signExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    user_sign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") user_sign record, @Param("example") user_signExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int updateByExample(@Param("record") user_sign record, @Param("example") user_signExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int updateByPrimaryKeySelective(user_sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign
     *
     * @mbg.generated Mon Jun 03 20:49:31 CST 2019
     */
    int updateByPrimaryKey(user_sign record);
}